create extension if not exists "pgcrypto";

create table if not exists public.study_state (
  user_id uuid primary key references auth.users(id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.practice_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  unit_ids integer[] not null default '{}',
  source text not null default 'All',
  score integer not null check (score >= 0),
  total integer not null check (total >= 0 and score <= total),
  started_at timestamptz,
  completed_at timestamptz not null default now(),
  device_info text
);

create index if not exists practice_sessions_user_completed_idx
  on public.practice_sessions (user_id, completed_at desc);

create table if not exists public.attempt_answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.practice_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id text not null,
  unit integer not null,
  topic text not null,
  prompt text not null,
  selected_answer text,
  correct_answer text not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now()
);

create index if not exists attempt_answers_user_topic_idx
  on public.attempt_answers (user_id, topic, answered_at desc);
create index if not exists attempt_answers_user_question_idx
  on public.attempt_answers (user_id, question_id);

create table if not exists public.generated_questions (
  id uuid primary key default gen_random_uuid(),
  external_id text unique,
  unit integer not null,
  topic text not null,
  source text not null default 'AI',
  difficulty smallint not null default 2 check (difficulty between 1 and 5),
  prompt text not null,
  choices jsonb not null,
  answer text not null,
  explanation_en text not null,
  explanation_zh text not null,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'rejected')),
  model text,
  generation_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  approved_at timestamptz
);

create index if not exists generated_questions_unit_status_idx
  on public.generated_questions (unit, status);

create table if not exists public.question_generation_jobs (
  id uuid primary key default gen_random_uuid(),
  requested_by uuid references auth.users(id) on delete set null,
  unit_ids integer[] not null,
  focus_topics text[] not null default '{}',
  requested_count integer not null check (requested_count between 1 and 100),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'completed', 'failed')),
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.study_state enable row level security;
alter table public.practice_sessions enable row level security;
alter table public.attempt_answers enable row level security;
alter table public.generated_questions enable row level security;
alter table public.question_generation_jobs enable row level security;

create policy "Users manage their study state"
  on public.study_state
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their own sessions"
  on public.practice_sessions
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users manage their own answers"
  on public.attempt_answers
  for all
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Authenticated users read approved generated questions"
  on public.generated_questions
  for select
  to authenticated
  using (status = 'approved');

create policy "Users read their own generation jobs"
  on public.question_generation_jobs
  for select
  to authenticated
  using ((select auth.uid()) = requested_by);
